version: '3.4'

services:
  moduit.interview.engine.docker.linux:
    image: moduit.interview-engine-docker-linux
    build:
      context: .
      dockerfile: Moduit.Interview.Engine.Docker.Linux/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
